### ISSUE TITLE
ng-repeat in caside won't work

### ISSUE THREAD

**Issue by PhoenixGrey** [PhoenixGrey/OODLIB#17]
When I use caside in my project, an error has occurred. 

Error: [ngRepeat:dupes] http://errors.angularjs.org/1.2.23/ngRepeat/dupes?p0=section%20in%20model.rawData&p1=undefined%3Aundefined
    at Error (native)
    at http://localhost:3000/thirdpartlib/angular/angular.min.js:6:450
    at http://localhost:3000/thirdpartlib/angular/angular.min.js:200:86
    at Object.fn (http://localhost:3000/thirdpartlib/angular/angular.min.js:108:344)
    at k.$digest (http://localhost:3000/thirdpartlib/angular/angular.min.js:109:403)
    at k.$apply (http://localhost:3000/thirdpartlib/angular/angular.min.js:112:398)
    at http://localhost:3000/thirdpartlib/angular/angular.min.js:18:270
    at Object.d [as invoke](http://localhost:3000/thirdpartlib/angular/angular.min.js:35:36)
    at c (http://localhost:3000/thirdpartlib/angular/angular.min.js:18:178)
    at Object.fc [as bootstrap](http://localhost:3000/thirdpartlib/angular/angular.min.js:18:387)

It should fix by adding track by $index.
[link](https://docs.angularjs.org/error/ngRepeat/dupes?p0=section%20in%20model.rawData&p1=undefined:undefined)

**Comment by PhoenixGrey** [comment]
Syntax error
